.TH aminoacids 7 2013-05-16 "Amino Acids"
.\"
.SH NAME
Amino Acids
.\"

.SH TABLE 1
The Standard Genetic Code

.TS
l l l.
full name	3 letter code	1 letter code
_
Alanine	Ala	A
Arginine	Arg	R
Asparagine	Asn	N
Aspartic Acid	Asp	D
Cysteine	Cys	C
Glutamic Acid	Glu	E
Glutamine	Gln	Q
Glycine	Gly	G
Histidine	His	H
Isoleucine	Ile	I
Leucine	Leu	L
Lysine	Lys	K
Methionine	Met	M
Phenylalanine	Phe	F
Proline	Pro	P
Serine	Ser	S
Threonine	Thr	T
Tryptophan	Trp	W
Tyrosine	Tyr	Y
Valine	Val	V
Stop	[*]	*
Unknown	[X]	X
.TE
.\"

.SH TABLE 2
The Standard Genetic Code

.TS
l l l.
1 letter code	3 letter code	full name
_
A	Ala	Alanine
C	Cys	Cysteine
D	Asp	Aspartic Acid
E	Glu	Glutamic Acid
F	Phe	Phenylalanine
G	Gly	Glycine
H	His	Histidine
I	Ile	Isoleucine
K	Lys	Lysine
L	Leu	Leucine
M	Met	Methionine
N	Asn	Asparagine
P	Pro	Proline
Q	Gln	Glutamine
R	Arg	Arginine
S	Ser	Serine
T	Thr	Threonine
V	Val	Valine
W	Trp	Tryptophan
X	[X]	Unknown
Y	Tyr	Tyrosine
*	[*]	Stop
.TE
.\"


.SH SEE ALSO
.BR geneticcode (7)
.BR acidnucleic (7)



