.TH nucleotides 7 2013-05-16 "Amino Acids"
.\"
.SH NAME
Nucleotides
.\"

.SH Description


.TS
l l l l.
Symbol	Description	Bases represented	Complement
_
A	Adenine	A	T
C	Cytosine	C	G
G	Guanine	G	C
T	Thymine	T	A
U	Uracil	U	A
_
B	not A (B comes after A)	C or G or T	V
D	not C (D comes after C)	A or G or T	H
H	not H (H comes after G)	A or C or T	D
K	keto	G or T	M
M	amino	A or C	K
N	any base	A or C or G or T	N
R	purine	A or G	Y
S	strong	C or G	S
V	not T (V comes after T and U)	A or C or G	B
W	weak	A or T	W
Y	pyrimidine	C or T	R
.TE
.\"


.SH SEE ALSO
.BR geneticcode (7)
.BR aminoacids (7)

