.TH nucleotides 7 2013-05-16 "Amino Acids"
.\"
.SH NAME
Nucleotides
.\"

.SH Description


.TS
l l l.
Symbol	Meaning	Complement
_
A	Adenine	T
C	Cytosine	G
G	Guanine	C
T	Thymine	A
_
U	Uracil	A
B	G or T or C	V
D	G or T or A	H
H	A or C or T	D
K	G or T	M
M	A or C	K
N	G or A or T or C	N
R	Purine (A or G)	Y
S	G or C	S
V	G or C or A	B
W	A or T	W
Y	Pyrimidine (C or T)	R
.TE
.\"


.SH SEE ALSO
.BR geneticcode (7)
.BR aminoacids (7)



