.TH samflags 7 2013-05-16 "SAM Flags"
.\"
.SH NAME
SAM flags \- bitwise flags for SAM.
.\"

.SH DESCRIPTION
The
.B SAM FLAGS
in plain english.

.TS
l l l.
Description	Hexa	Decimal
_
read paired	0x1	1
read mapped in proper pair	0x2	2
read unmapped	0x4	4
mate unmapped	0x8	8
read reverse strand	0x10	16
mate reverse strand	0x20	32
first in pair	0x40	64
second in pair	0x80	128
not primary alignment	0x100	256
read fails platform/vendor quality checks	0x200	512
read is PCR or optical duplicate	0x400	1024


.TE


.SH SEE ALSO
.BR sam (7)


